// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Examination.ViewModel;
using System.Data.Entity.Infrastructure;
using Examination.ViewModel;

namespace Examination.Models;

public partial class ExamContext : DbContext
{
    public ExamContext()
    {
    }

    public ExamContext(DbContextOptions<ExamContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Instructor_Course> Instructor_Courses { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Student_Answer> Student_Answers { get; set; }

    public virtual DbSet<Student_Course> Student_Courses { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    public virtual DbSet<Track_Course> TrackCourses { get; set; }

        

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseLazyLoadingProxies().UseSqlServer("Server=.;Database=ExaminationDB;Integrated Security=True;TrustServerCertificate=True;");
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.AId).HasName("PK__Admin__C69006288A1BE04D");

            entity.ToTable("Admin");
            entity.HasIndex(e => e.Aemail, "UQ__Admin__221408751DA40015").IsUnique();

            entity.HasIndex(e => e.Apassword, "UQ__Admin__93C2B8ED72C5F4B9").IsUnique();

            entity.Property(e => e.Aemail)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Aname)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Apassword)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Answer>(entity =>
        {
            entity.HasKey(e => e.AnswerId).HasName("PK__Answers__D4825004B2E6E4F4");

            entity.Property(e => e.Answerbody)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.QIdNavigation).WithMany(p => p.Answers)
                .HasForeignKey(d => d.QId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Answers_Questions");

        });

        modelBuilder.Entity<Student_Course>()
        .HasKey(sc => new { sc.SId, sc.CrId });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CrId).HasName("PK__Courses__AD761DA43839E327");

            entity.HasIndex(e => e.Cname, "UQ__Courses__9F5E029982D921FF").IsUnique();

            entity.Property(e => e.Cname)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Passgrade).HasDefaultValue(60);
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.EId).HasName("PK__Exams__C190176B4ADEEAEA");

            entity.HasOne(d => d.Cr).WithMany(p => p.Exams)
                .HasForeignKey(d => d.CrId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Exams_Courses");

            entity.HasOne(d => d.Ins).WithMany(p => p.Exams)
                .HasForeignKey(d => d.InsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Exams_Instructor");

            entity.HasOne(d => d.TIdNavigation).WithMany(p => p.Exams)
                .HasForeignKey(d => d.TId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Exams_Track");

            entity.HasMany(d => d.QIds).WithMany(p => p.EIds)
                .UsingEntity<Dictionary<string, object>>(
                    "Exams_Question",
                    r => r.HasOne<Question>().WithMany()
                        .HasForeignKey("QId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Exams_Questions_Questions"),
                    l => l.HasOne<Exam>().WithMany()
                        .HasForeignKey("EId")
                        .HasConstraintName("FK_Exams_Questions_Exams"),
                    j =>
                    {
                        j.HasKey("EId", "QId");
                        j.ToTable("Exams_Questions");
                    });
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.InsId).HasName("PK__Instruct__9D104DEFD1D63C97");

            entity.ToTable("Instructor");

            entity.HasIndex(e => e.Inspassword, "UQ__Instruct__569305E9FC645637").IsUnique();

            entity.HasIndex(e => e.Insemail, "UQ__Instruct__C14D26C13637B689").IsUnique();

            entity.Property(e => e.InsImg).HasMaxLength(50);
            entity.Property(e => e.Insemail)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Insgender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Insname)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Inspassword)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Inssalary).HasColumnType("decimal(18, 0)");
        });

        modelBuilder.Entity<Instructor_Course>(entity =>
        {
            entity.HasKey(e => new { e.InsId, e.CrId, e.TId });

            entity.HasOne(d => d.Cr).WithMany(p => p.Instructor_Courses)
                .HasForeignKey(d => d.CrId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Instructor_Courses_Courses");

            entity.HasOne(d => d.Ins).WithMany(p => p.Instructor_Courses)
                .HasForeignKey(d => d.InsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Instructor_Courses_Instructor");

            entity.HasOne(d => d.TIdNavigation).WithMany(p => p.Instructor_Courses)
                .HasForeignKey(d => d.TId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Instructor_Courses_Track");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.QId).HasName("PK__Question__CAB1462B7330046F");

            entity.HasIndex(e => e.Qbody, "UQ__Question__ABA745AF30EBB3DE").IsUnique();

            entity.Property(e => e.Qbody)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Qtype)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Cr).WithMany(p => p.Questions)
                .HasForeignKey(d => d.CrId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Questions_Courses");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.SId).HasName("PK__Students__CA195950F51D1EE6");

            entity.HasIndex(e => e.Semail, "UQ__Students__9E5E9EA8C5FE6B07").IsUnique();

            entity.Property(e => e.Semail)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Sgender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Sname)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.HasOne(d => d.Track).WithMany(p => p.Students)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Students_Track");
        });

        modelBuilder.Entity<Student_Answer>(entity =>
        {
            entity.HasKey(e => new { e.SId, e.EId, e.QId });

            entity.Property(e => e.SAnswer)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.EIdNavigation).WithMany(p => p.Student_Answers)
                .HasForeignKey(d => d.EId)
                .HasConstraintName("FK_Student_Answers_Exams");

            entity.HasOne(d => d.QIdNavigation).WithMany(p => p.Student_Answers)
                .HasForeignKey(d => d.QId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Answers_Questions");

            entity.HasOne(d => d.SIdNavigation).WithMany(p => p.Student_Answers)
                .HasForeignKey(d => d.SId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Answers_Students");
        });

        modelBuilder.Entity<Student_Course>(entity =>
        {
            entity.HasKey(e => new { e.SId, e.CrId });

            entity.HasOne(d => d.Cr).WithMany(p => p.Student_Courses)
                .HasForeignKey(d => d.CrId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Courses_Courses");

            entity.HasOne(d => d.SIdNavigation).WithMany(p => p.Student_Courses)
                .HasForeignKey(d => d.SId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Courses_Students");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => new { e.TopicName, e.CrId }).HasName("pk_topics");

            entity.Property(e => e.TopicName)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TopicDescription)
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Track>(entity =>
        {
            entity.HasKey(e => e.TId).HasName("PK__Track__C456D74914119846");

            entity.ToTable("Track");

            entity.HasIndex(e => e.Tname, "UQ__Track__48581FED5097F7BA").IsUnique();

            entity.Property(e => e.Tname)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Supervisor).WithMany(p => p.Tracks)
                .HasForeignKey(d => d.SupervisorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Track_Instructor");
        });

        modelBuilder.Entity<Track_Course>(entity =>
        {
            entity.HasKey(e => new { e.TId, e.Crid });

            entity.HasOne(d => d.Cr).WithMany(p => p.Track_Courses)
                .HasForeignKey(d => d.Crid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Track_Courses_Courses");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}