// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Admin 
{
    public int AId { get; set; }

    public string Aname { get; set; }

    public string Aemail { get; set; }

    public string Apassword { get; set; }
}