// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Answer
{
    public int AnswerId { get; set; }

    public string Answerbody { get; set; }

    public int QId { get; set; }

    public bool IsCorrect { get; set; }

    public virtual Question QIdNavigation { get; set; }
}