// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Course
{
    public int CrId { get; set; }

    public string Cname { get; set; }

    public int Passgrade { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Instructor_Course> Instructor_Courses { get; set; } = new List<Instructor_Course>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();

    public virtual ICollection<Track_Course> Track_Courses { get; set; } = new List<Track_Course>();
}