// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Instructor
{
    public int InsId { get; set; }

    public string Insname { get; set; }

    public string Insemail { get; set; }

    public string Inspassword { get; set; }

    public string Insgender { get; set; }

    public decimal Inssalary { get; set; }

    public string InsImg { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Instructor_Course> Instructor_Courses { get; set; } = new List<Instructor_Course>();

    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}