// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Question
{
    public int QId { get; set; }

    public string Qbody { get; set; }

    public string Qtype { get; set; }

    public int Qmark { get; set; }

    public int CrId { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual Course Cr { get; set; }

    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();

    public virtual ICollection<Exam> EIds { get; set; } = new List<Exam>();
}