// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Student_Course
{
    public int SId { get; set; }

    public int CrId { get; set; }

    public int? degree { get; set; }

    public virtual Course Cr { get; set; }

    public virtual Student SIdNavigation { get; set; }
}