// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Student
{
    public int SId { get; set; }

    public string Sname { get; set; }

    public string Semail { get; set; }

    public string password { get; set; }

    public string Sgender { get; set; }

    public int TrackId { get; set; }

    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();

    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();

    public virtual Track Track { get; set; }
}