// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Student_Answer
{
    public int SId { get; set; }

    public int EId { get; set; }

    public int QId { get; set; }

    public string SAnswer { get; set; }

    public virtual Exam EIdNavigation { get; set; }

    public virtual Question QIdNavigation { get; set; }

    public virtual Student SIdNavigation { get; set; }
}