// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Track
{
    public int TId { get; set; }

    public string Tname { get; set; }

    public int SupervisorId { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Instructor_Course> Instructor_Courses { get; set; } = new List<Instructor_Course>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual Instructor Supervisor { get; set; }
}