// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models;

public partial class Track_Course
{
    public int TId { get; set; }

    public int Crid { get; set; }

    public virtual Course Cr { get; set; }
}